FROM ubuntu:latest
RUN apt-get update && apt-get install -y python3 python3-pip
WORKDIR /app
COPY requirements.txt .
RUN pip3 install --user -r requirements.txt
COPY app.py .
RUN chmod +x app.py
CMD ["python3", "app.py"]